[package]
name = "pi"
version = "0.1.0"
authors = ["masataka.momoki <masataka.momoki@cac.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
